[package]
name = "bench-serialize"
version = "0.1.0"
authors = ["hagure-kusa"]
edition = "2018"

[dependencies]
serde = "1.0.114"
serde_derive = "1.0.114"
serde_bytes = "0.11.5"

rmp-serde = "0.14.3"
serde_cbor = "0.11.1"
bincode = "1.3.1"
